server:
  port: 13555
Spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 64MB
      max-request-size: 100MB
excel-utils:
  import-max-parallel: 4
  async-refresh-milliseconds: 1500
  async-import-max-fail: 100
knife4j:
  enable: true
  setting:
    language: zh_cn