server:
  port: 13555
Spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 64MB
      max-request-size: 100MB
excel-utils:
  import-max-parallel: 4
  async-refresh-milliseconds: 1500
  async-import-max-fail: 100
swagger-config:
  enable: true
  protocol: http
  base-package: cn.creekmoon.excelUtils.example
  title: 导入导出测试API
  version: 1.0
  description: 导入导出测试API